[package]
name = "melcher_io"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html-site-generator = { version = "0.0.1-alpha", path = "../html-site-generator" }
once_cell = "1.18.0"
