version: '3.8'

services:
  website:
    build: .
    restart: always
  
  cloudflared:
    image: ubunut_cloudflared:latest
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./certs:/.cloudflared/cert.pem
    links:
      - website
    depends_on:
      - website
    entrypoint: /bin/bash
