version: '3.8'

services:
  website:
    container_name: melcher_io_website
    build: .
    links:
      - webhook_handler
    ports:
      - 8080:80
      - 80:80
      - 443:80

  webhook_handler:
    build: ./github_webhook_handler
    restart: always
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./webhook.env
